#!/bin/bash


# Execute job in the queue "std.q" unless you have special requirements.
#$ -q std.q

# The batch system should use the current directory as working directory.
#$ -cwd

# Name your job. Unless you use the -o and -e options, output will
# go to a unique file name.ojob_id for each job.
#$ -N n-body

# Redirect output stream to this file.
#$ -o data_.dat

# Join the error stream to the output stream.
#$ -j yes

N=10000

for (( i=0;i < $N; i+=10 ))
do
    ./n-body $i 1000
done

