#!/bin/bash


# Execute job in the queue "std.q" unless you have special requirements.
#$ -q std.q

# The batch system should use the current directory as working directory.
#$ -cwd

# Name your job. Unless you use the -o and -e options, output will
# go to a unique file name.ojob_id for each job.
#$ -N real_seq

# Redirect output stream to this file.
#$ -o real_seq.dat

# Join the error stream to the output stream.
#$ -j yes

#$ -l exclusive=true

time ./real &> /dev/null
    

